import { createFileRoute } from "@tanstack/react-router";
import { SiteLayout, EMAIL } from "@/components/SiteLayout";
import { DataStreamDivider, MOTIF_MONO_LABEL } from "@/components/ChapterMotifs";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — Intelligent Integrations" },
      { name: "description", content: "Terms of service for Intelligent Integrations covering getaiintegrations.com and our WhatsApp/SMS conversational AI messaging services." },
      { property: "og:title", content: "Terms of Service — Intelligent Integrations" },
      { property: "og:description", content: "Terms governing use of Intelligent Integrations' website and messaging services." },
      { property: "og:type", content: "website" },
      { property: "og:url", content: "https://getaiintegrations.com/terms" },
      { name: "twitter:card", content: "summary" },
    ],
    links: [{ rel: "canonical", href: "https://getaiintegrations.com/terms" }],
  }),
  component: TermsPage,
});

function Section({ n, title, children }: { n: string; title: string; children: React.ReactNode }) {
  return (
    <section className="mt-14 first:mt-0">
      <p className={MOTIF_MONO_LABEL}>
        <span className="text-primary/80">{"//"}</span>{" "}
        <span className="tabular-nums text-foreground/80">{n}</span>
        <span className="mx-2 text-black/25">—</span>
        <span>{title}</span>
      </p>
      <div className="mt-4 space-y-4 text-[15px] leading-relaxed text-foreground/80">{children}</div>
      <div className="mt-10">
        <DataStreamDivider />
      </div>
    </section>
  );
}

function TermsPage() {
  return (
    <SiteLayout>
      <article className="mx-auto max-w-3xl px-6 py-24 md:py-32">
        <header>
          <p className={MOTIF_MONO_LABEL}>Legal · Effective July 25, 2026</p>
          <h1 className="mt-4 font-display text-5xl leading-[1.05] tracking-tight text-foreground md:text-6xl">
            Terms of Service
          </h1>
          <p className="mt-6 text-lg text-muted-foreground">
            The terms governing your use of getaiintegrations.com and our conversational AI
            messaging services.
          </p>
        </header>

        <div className="mt-14">
          <DataStreamDivider />
        </div>

        <Section n="01" title="Acceptance">
          <p>
            By using getaiintegrations.com or messaging our AI services via WhatsApp or SMS, you
            agree to these Terms of Service.
          </p>
        </Section>

        <Section n="02" title="Description of Services">
          <p>
            We provide a professional portfolio and advisory-inquiry website, as well as
            experimental conversational AI agents accessible via WhatsApp and SMS, powered by
            third-party AI models. AI responses are automatically generated.
          </p>
        </Section>

        <Section n="03" title="Messaging Terms">
          <p>
            All conversations are user-initiated. There are no subscriptions or recurring
            marketing messages. Message frequency varies based on your interaction. Message and
            data rates may apply per your carrier. Reply <strong className="text-foreground">STOP</strong>
            {" "}to opt out and <strong className="text-foreground">HELP</strong> for help. Service
            availability is not guaranteed and may be interrupted, modified, or discontinued at
            any time.
          </p>
        </Section>

        <Section n="04" title="AI Disclaimer">
          <p>
            Responses are generated by AI and may be inaccurate, incomplete, or unsuitable for
            your purposes. Content is provided for informational and experimental purposes only
            and does not constitute professional, legal, medical, or financial advice. You assume
            all risk arising from reliance on AI-generated content.
          </p>
        </Section>

        <Section n="05" title="Acceptable Use">
          <p>
            No unlawful, abusive, harassing, or fraudulent use. No attempts to disrupt, reverse
            engineer, or abuse the services. We may block or terminate access for violations.
          </p>
        </Section>

        <Section n="06" title="Intellectual Property">
          <p>
            Site content, branding, and design are owned by Joseph Bisaccia and Intelligent
            Integrations. You may not reproduce them without permission.
          </p>
        </Section>

        <Section n="07" title="Disclaimer of Warranties">
          <p>
            Services are provided "AS IS" and "AS AVAILABLE" without warranties of any kind,
            express or implied.
          </p>
        </Section>

        <Section n="08" title="Limitation of Liability">
          <p>
            To the maximum extent permitted by law, we are not liable for indirect, incidental,
            special, or consequential damages arising from use of the site or messaging services.
          </p>
        </Section>

        <Section n="09" title="Indemnification">
          <p>
            You agree to indemnify and hold us harmless against claims arising from your misuse of
            the services.
          </p>
        </Section>

        <Section n="10" title="Governing Law">
          <p>
            These terms are governed by the laws of the United States and the State of Arizona.
          </p>
        </Section>

        <Section n="11" title="Changes">
          <p>
            We may revise these terms from time to time. Continued use constitutes acceptance.
          </p>
        </Section>

        <Section n="12" title="Contact">
          <p>
            Questions about these terms? Email{" "}
            <a href={`mailto:${EMAIL}`} className="text-primary underline-offset-4 hover:underline">
              {EMAIL}
            </a>
            .
          </p>
        </Section>
      </article>
    </SiteLayout>
  );
}
